### ISSUE TITLE
Handle the max connections on connect

### ISSUE THREAD

**Issue by tinchoz49** [RangerMauve/mostly-minimal-spanning-tree#1]
Hi @RangerMauve 

Suppose that the max peers is 4 (default) and I already have 3 connections.

What happen if during an async connect (https://github.com/RangerMauve/mostly-minimal-spanning-tree/blob/master/index.js#L138) I get a incoming connection too?

If the connect finish **first**, I add the connection to the list and the incoming connection is going to be rejected beacause the reached max peer.

But if the connect happen **after** the incoming connection, we don't check how many connections we have and I end up with 5 connections.

Should we do some check like the `shouldHandleIncoming` in this case? Like:
```javascript
const connection = await this._connect(peer)

if (!this.shouldHandleIncoming()) {
  connection.close()
  break
}

connected = true
this.addConnection(peer, connection)

// Listen on the connection close to invoke `run` again
connection.once('end', () => {
  this.run()
})
```

**Comment by RangerMauve** [comment]
I think I left it that way so that you'd always have at least one outgoing connection since that's needed to make the algorithm converge on a good shape.

Ideally, if the incoming connection fails, that peer should be able to connect to the next available peer.

Does this change have any adverse effects like creating more network partitions? (testing in the simulator)

**Comment by tinchoz49** [comment]
It's true, it was something that I misunderstood. Thanks.
